### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by arjellel** [harrego/yt-scraper#9]
i only get the id and the url thats all :/
![image](https://user-images.githubusercontent.com/52532423/86845456-37bbfd00-c0b2-11ea-8351-a96bc6cc26eb.png)

**Comment by harrego** [comment]
YouTube retired the legacy "about page" therefore changing the layout that the module currently relies on. I'm working on a fix that will be out in a few hours and will rely on the JSON info given by the page rather than scraping the HTML.

**Comment by harrego** [comment]
Fixed with version 2.1.0! `channelInfo` now provides some new info too, check the updated docs for more.
